name: Daily Version Catalog Update

on:
  schedule:
    - cron: '15 19 * * *' # Daily at 19:15 UTC (04:15 JST)
  workflow_dispatch:

concurrency:
  group: version-catalog-update
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version-catalog:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for accurate diff

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run version catalog update
        run: ./gradlew --no-daemon versionCatalogUpdate

      - name: Verify build & tests
        run: ./gradlew --no-daemon build

      - name: Determine branch name
        run: echo "BRANCH_NAME=chore/version-catalog-update-$(date +'%Y%m%d')" >> "$GITHUB_ENV"

      - name: Create Pull Request if changes
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "chore: update version catalog"
          commit-message: "chore: update version catalog"
          body: |
            Automated daily dependency version catalog update.

            This PR was generated by the scheduled GitHub Actions workflow.
            Task executed: `./gradlew versionCatalogUpdate` followed by a full `./gradlew build` to ensure the update passes compile, lint, and tests.

            Only stable, pinned major/minor (patch-level) updates are considered per plugin configuration.
          labels: dependencies, automated
          add-paths: |
            gradle/libs.versions.toml
          signoff: false
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          draft: false

      - name: Output result
        if: steps.create-pull-request.outputs.pull-request-number
        run: echo "Created/updated PR #${{ steps.create-pull-request.outputs.pull-request-number }}"
